grid_map_topic: /south_grid_map/local_grid_map/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: mean
  - name: traversability_grid
    type: occupancy_grid
    params:
     layer: mean
     data_min: 0.0
     data_max: 0.5
