grid_map_topic: /local_grid_map/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
  - name: traversability_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: -4.0
     data_max: 1.0
